name: 1Hour Bot Run

on:
  schedule:
    - cron: '0 * * * *'  # 매 정각마다 실행
  workflow_dispatch:      # 수동 실행 버튼 생성

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests beautifulsoup4 python-telegram-bot
      - name: Run Bot
        run: python main.py
      - name: Keep changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add last_titles.txt
          git commit -m "Update last titles" || exit 0
          git push
