name: 1Hour Bot Run

on:
  schedule:
    - cron: '0 * * * *'  # 매 정각마다 실행
  workflow_dispatch:      # 수동 실행 버튼 생성

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 파일 쓰기 권한 허용
    steps:
      - uses: actions/checkout@v3
